services:
  postgres:
    image: postgres
    ports:
       - ":5432"
    environment:
        POSTGRES_PASSWORD: 1234
    networks:
       - backend

  heritage.webapi:
    image: ${DOCKER_REGISTRY-}heritagewebapi
    build:
      context: .
      dockerfile: Heritage.WebApi/Dockerfile
    depends_on:
       - postgres
    networks:
       - backend

networks:
  backend: